//IIFE(IMMEDIATE INVOKE FUNCTION)
// create  function name with out name  * with is not have a name in function  *using

// var result=(function (){
//     console.log("annonymous function");
    
// })(); //to use backend work this method ; importen 

// (function(){
//  //some code
// }()); 
    


// var result = (function() {
//     var x = 10;
//     var y = 20;
//     return x + y;
// })();

// console.log(result);

// var result =(function(){
//     var x=10;
//     var y=20;
//     return x+y;
// }) ();



//callback function this a higher order function
 function calculator(a,b,operation){
      
 }
